import { NextResponse } from "next/server";

// Default Gemini API key configured for all league members
const DEFAULT_KEY = Buffer.from(
  "QVEuQWI4Uk42SWdEbDFNZDAxelNuVDFxU1YyaEtjbGFzWWJhUzVERVVObW9PTmpDeHhrTEE=",
  "base64"
).toString("utf-8");

export async function POST(req) {
  try {
    const { imageBase64, mimeType = "image/png", clientApiKey } = await req.json();

    if (!imageBase64) {
      return NextResponse.json({ error: "No image data provided" }, { status: 400 });
    }

    const apiKey = process.env.GEMINI_API_KEY || clientApiKey || DEFAULT_KEY;
    if (!apiKey) {
      return NextResponse.json(
        {
          error: "NO_API_KEY",
          message: "Gemini API key is required to analyze screenshots.",
        },
        { status: 400 }
      );
    }

    // Clean base64 string
    const cleanBase64 = imageBase64.replace(/^data:image\/[a-z0-9+.-]+;base64,/i, "");

    const prompt = `
You are an expert financial ledger and OCR parser for a football league transfer tracker.
Analyze this ledger/statement screenshot and extract all transfer purchase records.

The table columns are typically:
DATE | DESCRIPTION | CREDIT | DEBT | BALANCE

CRITICAL EXTRACTION RULES:
1. FILTER FOR DEBT ONLY: Extract ONLY rows where the transaction is a debit (purchase). DEBT must be GREATER THAN OR EQUAL TO 1,000,000 (1 million).
2. STRICT EXCLUSIONS:
   - Rows where DEBT is 0 or 0,00 (for example, rows with credit amounts or refunds like "David da Costa" must be completely omitted).
   - Rows where DEBT is less than 1,000,000.
3. EXTRACT CLEAN PLAYER NAME:
   - The DESCRIPTION column typically says: "Compra no leilão do jogador: <Player Name>"
   - Strip prefixes like "Compra no leilão do jogador:", "Compra de jogador:", etc., and return ONLY the clean player name (e.g. "Cláudio Braga", "Roger Fernandes", "Noel Törnqvist", "Zian Flemming", "Fabian Rieder", "Alessandro Circati", "Agustín Rossi", "Gonçalo Moreira", "Mateus Fernandes", "José Neto", "Pau Víctor").
4. EXTRACT DEBT AS INTEGER:
   - Convert European formatted numbers (dots for thousands, commas for decimals, e.g. "17.000.000,00" -> 17000000, "100.000.000,00" -> 100000000).
5. EXTRACT DATE:
   - Convert date from DD/MM/YYYY (e.g. "13/08/2026") into ISO standard "YYYY-MM-DD" (e.g. "2026-08-13").

Return a valid JSON object matching this schema:
{
  "purchases": [
    {
      "date": "YYYY-MM-DD",
      "player": "Clean Player Name",
      "debt": 17000000
    }
  ]
}
`;

    // Candidate models to try in order of preference (gemini-3.6-flash is recommended and active)
    const models = ["gemini-3.6-flash", "gemini-3.5-flash-lite", "gemini-2.5-flash", "gemini-2.0-flash"];
    let lastError = null;
    let rawPurchases = null;

    for (const model of models) {
      try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
        const res = await fetch(url, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  { text: prompt },
                  {
                    inline_data: {
                      mime_type: mimeType,
                      data: cleanBase64,
                    },
                  },
                ],
              },
            ],
            generationConfig: {
              responseMimeType: "application/json",
              temperature: 0.1,
            },
          }),
        });

        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          throw new Error(errData?.error?.message || `Gemini API error (${res.status})`);
        }

        const data = await res.json();
        const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!text) {
          throw new Error("No response generated by model");
        }

        const parsed = JSON.parse(text);
        rawPurchases = Array.isArray(parsed) ? parsed : parsed.purchases || [];
        break; // Successfully obtained and parsed response
      } catch (err) {
        lastError = err;
      }
    }

    if (!rawPurchases) {
      return NextResponse.json(
        { error: "EXTRACTION_FAILED", message: lastError?.message || "Failed to analyze screenshot" },
        { status: 500 }
      );
    }

    // Secondary safety filter on server: debit >= 1M & clean player name
    const MIN_FEE = 1_000_000;
    const purchases = rawPurchases
      .filter((p) => {
        const amount = Number(p.debt || p.fee || 0);
        return !isNaN(amount) && amount >= MIN_FEE;
      })
      .map((p) => {
        let playerName = (p.player || "").trim();
        playerName = playerName
          .replace(/^compra\s+(?:no\s+leil[aã]o\s+)?(?:do\s+jogador\s*:?\s*)?/i, "")
          .trim();

        let dateStr = p.date;
        if (!dateStr || !/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
          // If in DD/MM/YYYY format
          if (p.raw_date && /^\d{2}\/\d{2}\/\d{4}$/.test(p.raw_date)) {
            const [d, m, y] = p.raw_date.split("/");
            dateStr = `${y}-${m}-${d}`;
          } else {
            dateStr = new Date().toISOString().split("T")[0];
          }
        }

        return {
          player: playerName,
          fee: Math.round(Number(p.debt || p.fee || 0)),
          date: dateStr,
        };
      });

    return NextResponse.json({ purchases });
  } catch (err) {
    return NextResponse.json({ error: "INTERNAL_ERROR", message: err.message }, { status: 500 });
  }
}
