import { NextResponse } from "next/server";

// Default Gemini API key configured for all league members
const DEFAULT_KEY = Buffer.from(
  "QVEuQWI4Uk42SWdEbDFNZDAxelNuVDFxU1YyaEtjbGFzWWJhUzVERVVObW9PTmpDeHhrTEE=",
  "base64"
).toString("utf-8");

const PROMPT = `
You are an expert financial ledger and OCR parser for a football league transfer tracker.
Analyze this ledger/statement screenshot and extract all transfer purchase records.

The table columns are typically:
DATE | DESCRIPTION | CREDIT | DEBT | BALANCE

CRITICAL EXTRACTION RULES:
1. FILTER FOR DEBT ONLY: Extract ONLY rows where the transaction is a debit (purchase). DEBT must be GREATER THAN OR EQUAL TO 1,000,000 (1 million).
2. STRICT EXCLUSIONS:
   - Rows where DEBT is 0 or 0,00 (for example, rows with credit amounts or refunds like "David da Costa" must be completely omitted).
   - Rows where DEBT is less than 1,000,000.
3. EXTRACT CLEAN PLAYER NAME:
   - The DESCRIPTION column typically says: "Compra no leilão do jogador: <Player Name>"
   - Strip prefixes like "Compra no leilão do jogador:", "Compra de jogador:", etc., and return ONLY the clean player name (e.g. "Cláudio Braga", "Roger Fernandes", "Noel Törnqvist", "Zian Flemming", "Fabian Rieder", "Alessandro Circati", "Agustín Rossi", "Gonçalo Moreira", "Mateus Fernandes", "José Neto", "Pau Víctor").
4. EXTRACT DEBT AS INTEGER:
   - Convert European formatted numbers (dots for thousands, commas for decimals, e.g. "17.000.000,00" -> 17000000, "100.000.000,00" -> 100000000).
5. EXTRACT DATE:
   - Convert date from DD/MM/YYYY (e.g. "13/08/2026") into ISO standard "YYYY-MM-DD" (e.g. "2026-08-13").

Return a valid JSON object matching this schema:
{
  "purchases": [
    {
      "date": "YYYY-MM-DD",
      "player": "Clean Player Name",
      "debt": 17000000
    }
  ]
}
`;

async function scanSingleImage(cleanBase64, mimeType, apiKey) {
  // Candidate models to try in order of preference
  const models = [
    "gemini-3.6-flash",
    "gemini-3.5-flash-lite",
    "gemini-3.5-flash",
    "gemini-flash-latest",
  ];
  let lastError = null;

  for (const model of models) {
    // Attempt up to 2 times per model in case of temporary 503 spike
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
        const res = await fetch(url, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  { text: PROMPT },
                  {
                    inline_data: {
                      mime_type: mimeType,
                      data: cleanBase64,
                    },
                  },
                ],
              },
            ],
            generationConfig: {
              responseMimeType: "application/json",
              temperature: 0.1,
            },
          }),
        });

        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          const errMsg = errData?.error?.message || `Gemini API error (${res.status})`;
          if (res.status === 503 && attempt === 0) {
            // Wait 600ms before quick retry
            await new Promise((r) => setTimeout(r, 600));
            continue;
          }
          throw new Error(errMsg);
        }

        const data = await res.json();
        const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!text) {
          throw new Error("No response generated by model");
        }

        const parsed = JSON.parse(text);
        return Array.isArray(parsed) ? parsed : parsed.purchases || [];
      } catch (err) {
        lastError = err;
        // If not 503 retryable, break to next model
        if (!err.message?.includes("503") && !err.message?.includes("demand")) {
          break;
        }
      }
    }
  }

  throw lastError || new Error("Failed to analyze screenshot");
}

export async function POST(req) {
  try {
    const body = await req.json();
    const { imageBase64, mimeType = "image/png", images = [], clientApiKey } = body;

    const apiKey = process.env.GEMINI_API_KEY || (clientApiKey && clientApiKey.trim()) || DEFAULT_KEY;
    if (!apiKey) {
      return NextResponse.json(
        {
          error: "NO_API_KEY",
          message: "Gemini API key is required to analyze screenshots.",
        },
        { status: 400 }
      );
    }

    // Support single image or multiple images in one request
    const imageList = [];
    if (Array.isArray(images) && images.length > 0) {
      for (const img of images) {
        const raw = typeof img === "string" ? img : img?.imageBase64 || img?.dataUrl;
        if (raw) {
          imageList.push({
            cleanBase64: raw.replace(/^data:image\/[a-z0-9+.-]+;base64,/i, ""),
            mimeType: (typeof img === "object" && img?.mimeType) || "image/png",
          });
        }
      }
    } else if (imageBase64) {
      imageList.push({
        cleanBase64: imageBase64.replace(/^data:image\/[a-z0-9+.-]+;base64,/i, ""),
        mimeType,
      });
    }

    if (imageList.length === 0) {
      return NextResponse.json({ error: "No image data provided" }, { status: 400 });
    }

    // Process all images concurrently with Promise.allSettled
    const settled = await Promise.allSettled(
      imageList.map((img) => scanSingleImage(img.cleanBase64, img.mimeType, apiKey))
    );

    const rawPurchases = [];
    const errors = [];
    settled.forEach((res, i) => {
      if (res.status === "fulfilled") {
        rawPurchases.push(...res.value);
      } else {
        errors.push(`Image #${i + 1}: ${res.reason?.message || "Failed to analyze"}`);
      }
    });

    if (rawPurchases.length === 0 && errors.length > 0) {
      throw new Error(errors.join(" | "));
    }

    // Secondary safety filter on server: debit >= 1M & clean player name
    const MIN_FEE = 1_000_000;
    const purchases = rawPurchases
      .filter((p) => {
        const amount = Number(p.debt || p.fee || 0);
        return !isNaN(amount) && amount >= MIN_FEE;
      })
      .map((p) => {
        let playerName = (p.player || "").trim();
        playerName = playerName
          .replace(/^compra\s+(?:no\s+leil[aã]o\s+)?(?:do\s+jogador\s*:?\s*)?/i, "")
          .trim();

        let dateStr = p.date;
        if (!dateStr || !/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
          // If in DD/MM/YYYY format
          if (p.raw_date && /^\d{2}\/\d{2}\/\d{4}$/.test(p.raw_date)) {
            const [d, m, y] = p.raw_date.split("/");
            dateStr = `${y}-${m}-${d}`;
          } else {
            dateStr = new Date().toISOString().split("T")[0];
          }
        }

        return {
          player: playerName,
          fee: Math.round(Number(p.debt || p.fee || 0)),
          date: dateStr,
        };
      });

    return NextResponse.json({ purchases });
  } catch (err) {
    return NextResponse.json({ error: "INTERNAL_ERROR", message: err.message }, { status: 500 });
  }
}
