// Maps pesdb.net "nationality" strings to ISO 3166-1 alpha-2 codes so we can
// render a flag image next to search results. Not exhaustive — falls back to
// no flag for anything unmapped rather than guessing.
const COUNTRY_CODES = {
  England: "GB-ENG",
  Scotland: "GB-SCT",
  Wales: "GB-WLS",
  "Northern Ireland": "GB-NIR",
  "Republic of Ireland": "IE",
  Ireland: "IE",
  France: "FR",
  Germany: "DE",
  Spain: "ES",
  Italy: "IT",
  Portugal: "PT",
  Netherlands: "NL",
  Belgium: "BE",
  Switzerland: "CH",
  Austria: "AT",
  Sweden: "SE",
  Norway: "NO",
  Denmark: "DK",
  Finland: "FI",
  Iceland: "IS",
  Poland: "PL",
  Ukraine: "UA",
  Russia: "RU",
  Turkey: "TR",
  Croatia: "HR",
  Serbia: "RS",
  Slovenia: "SI",
  Slovakia: "SK",
  "Czech Republic": "CZ",
  Czechia: "CZ",
  Hungary: "HU",
  Romania: "RO",
  Bulgaria: "BG",
  Greece: "GR",
  Israel: "IL",
  Albania: "AL",
  "North Macedonia": "MK",
  "Bosnia and Herzegovina": "BA",
  Montenegro: "ME",
  Kosovo: "XK",
  Georgia: "GE",
  Armenia: "AM",
  Azerbaijan: "AZ",
  Belarus: "BY",
  Estonia: "EE",
  Latvia: "LV",
  Lithuania: "LT",
  Luxembourg: "LU",
  Malta: "MT",
  Cyprus: "CY",
  Andorra: "AD",
  "San Marino": "SM",
  "Faroe Islands": "FO",
  Gibraltar: "GI",
  Kazakhstan: "KZ",
  Uzbekistan: "UZ",
  Moldova: "MD",

  Brazil: "BR",
  Argentina: "AR",
  Uruguay: "UY",
  Colombia: "CO",
  Chile: "CL",
  Peru: "PE",
  Ecuador: "EC",
  Paraguay: "PY",
  Bolivia: "BO",
  Venezuela: "VE",
  Mexico: "MX",
  "Costa Rica": "CR",
  Panama: "PA",
  Jamaica: "JM",
  Honduras: "HN",
  "United States": "US",
  USA: "US",
  Canada: "CA",

  Japan: "JP",
  "South Korea": "KR",
  "Korea Republic": "KR",
  China: "CN",
  "China PR": "CN",
  India: "IN",
  Indonesia: "ID",
  Thailand: "TH",
  Vietnam: "VN",
  Malaysia: "MY",
  Philippines: "PH",
  "Saudi Arabia": "SA",
  Qatar: "QA",
  "United Arab Emirates": "AE",
  UAE: "AE",
  Iran: "IR",
  Iraq: "IQ",
  Jordan: "JO",
  Lebanon: "LB",
  Syria: "SY",
  Kuwait: "KW",
  Bahrain: "BH",
  Oman: "OM",
  Yemen: "YE",
  Palestine: "PS",
  "North Korea": "KP",
  Mongolia: "MN",

  Nigeria: "NG",
  Senegal: "SN",
  Morocco: "MA",
  Egypt: "EG",
  Algeria: "DZ",
  Tunisia: "TN",
  Ghana: "GH",
  Cameroon: "CM",
  "Ivory Coast": "CI",
  "Cote d'Ivoire": "CI",
  Mali: "ML",
  "Burkina Faso": "BF",
  "DR Congo": "CD",
  "Congo DR": "CD",
  Zambia: "ZM",
  Kenya: "KE",
  Ethiopia: "ET",
  Angola: "AO",
  Gabon: "GA",
  Guinea: "GN",
  "Cape Verde": "CV",
  "South Africa": "ZA",
  Uganda: "UG",
  Tanzania: "TZ",

  Australia: "AU",
  "New Zealand": "NZ",
  Fiji: "FJ",
  "Papua New Guinea": "PG",
};

// Flag emoji are unreliable on Windows (many fonts render the ISO code as
// plain text instead of a flag glyph), so use real flag images from
// flagcdn.com instead. It supports both ISO 3166-1 (fr, pt, br...) and the
// UK constituent countries (gb-eng, gb-sct, gb-wls) in the same lowercase,
// hyphenated format we already store in COUNTRY_CODES.
export function getFlagUrl(nationality) {
  if (!nationality) return null;
  const code = COUNTRY_CODES[nationality.trim()];
  if (!code) return null;
  return `https://flagcdn.com/${code.toLowerCase()}.svg`;
}
