import { NextResponse } from "next/server";

// Default Gemini API key configured for all league members
const DEFAULT_KEY = Buffer.from(
  "QVEuQWI4Uk42SWdEbDFNZDAxelNuVDFxU1YyaEtjbGFzWWJhUzVERVVObW9PTmpDeHhrTEE=",
  "base64"
).toString("utf-8");

const PROMPT = `
You are an expert OCR and data extraction parser for football league player trades.
Analyze this 'Trade - Details' modal screenshot and extract the trade information.

There are two sides in the trade exchange:
- Side A: The user/club on the left
- Side B: The user/club on the right

Extract:
1. userA: The username or club name on the left (e.g. "JohnnyRainbow"). Strip "User:" or "Club:".
2. playerA: The clean player name on the left (e.g. "Amadou Onana").
3. userB: The username or club name on the right (e.g. "gradism"). Strip "User:" or "Club:".
4. playerB: The clean player name on the right (e.g. "Malcom").
5. cashPayer: Which user/club pays additional cash compensation:
   - "teamA" if the left side has "+ <amount>"
   - "teamB" if the right side has "+ <amount>"
   - "none" if it is a straight swap with no cash.
6. cashAmount: The numeric integer of cash compensation if any (e.g. "9.500.000,00" -> 9500000). If none, 0.

Return a valid JSON object matching this exact schema:
{
  "userA": "Username or Team A",
  "playerA": "Player A Name",
  "userB": "Username or Team B",
  "playerB": "Player B Name",
  "cashPayer": "teamA" | "teamB" | "none",
  "cashAmount": 9500000
}
`;

async function scanTradeImage(cleanBase64, mimeType, apiKey) {
  const models = [
    "gemini-3.6-flash",
    "gemini-3.5-flash-lite",
    "gemini-3.5-flash",
    "gemini-flash-latest",
  ];
  let lastError = null;

  for (const model of models) {
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
        const res = await fetch(url, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  { text: PROMPT },
                  {
                    inline_data: {
                      mime_type: mimeType,
                      data: cleanBase64,
                    },
                  },
                ],
              },
            ],
            generationConfig: {
              responseMimeType: "application/json",
              temperature: 0.1,
            },
          }),
        });

        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          const errMsg = errData?.error?.message || `Gemini API error (${res.status})`;
          if (res.status === 503 && attempt === 0) {
            await new Promise((r) => setTimeout(r, 600));
            continue;
          }
          throw new Error(errMsg);
        }

        const data = await res.json();
        const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!text) {
          throw new Error("No response generated by model");
        }

        const parsed = JSON.parse(text);
        return parsed;
      } catch (err) {
        lastError = err;
        if (!err.message?.includes("503") && !err.message?.includes("demand")) {
          break;
        }
      }
    }
  }

  throw lastError || new Error("Failed to analyze trade screenshot");
}

export async function POST(req) {
  try {
    const body = await req.json();
    const { imageBase64, mimeType = "image/png", clientApiKey } = body;

    const apiKey = process.env.GEMINI_API_KEY || (clientApiKey && clientApiKey.trim()) || DEFAULT_KEY;
    if (!apiKey) {
      return NextResponse.json(
        {
          error: "NO_API_KEY",
          message: "Gemini API key is required to analyze screenshots.",
        },
        { status: 400 }
      );
    }

    if (!imageBase64) {
      return NextResponse.json({ error: "No image data provided" }, { status: 400 });
    }

    const cleanBase64 = imageBase64.replace(/^data:image\/[a-z0-9+.-]+;base64,/i, "");
    const parsed = await scanTradeImage(cleanBase64, mimeType, apiKey);

    // Normalize output fields
    const trade = {
      userA: (parsed?.userA || "").replace(/^user:\s*/i, "").trim(),
      playerA: (parsed?.playerA || "").trim(),
      userB: (parsed?.userB || "").replace(/^user:\s*/i, "").trim(),
      playerB: (parsed?.playerB || "").trim(),
      cashPayer: ["teamA", "teamB"].includes(parsed?.cashPayer) ? parsed.cashPayer : "none",
      cashAmount: Math.round(Number(parsed?.cashAmount || 0)),
    };

    return NextResponse.json({ trade });
  } catch (err) {
    return NextResponse.json({ error: "INTERNAL_ERROR", message: err.message }, { status: 500 });
  }
}
